### ISSUE TITLE
some events are not working

### ISSUE THREAD

**Issue by ischon** [Warped2713/Discord-GitLab-Webhook#7] opened 2017-12-20 07:42 UTC
the events:

- Tag push events
- Job events
- Pipeline events
- ~Wiki Page events~

are not working

please fix these as soon as possible

**Comment by 23nd** [comment] 2018-01-03 16:28
Hi @pokemonspeler 

I will try to implement Tag, Job, and Pipeline events sometime this week.

What part of Wiki Page events is not working?

**Comment by ischon** [comment] 2018-01-03 16:37
Hi @warped2713,

The wiki page event didn’t work when I tried it from the webhook test. I now think it might be something with the fact that there isn’t a wiki on the GitLab instance where I tested this.

Could you make the config more human friendly or create a better explanation about the config, it was troublesome to configure it not bowing what data I precesly needed. Thanx in advance

**Comment by 23nd** [comment] 2018-01-03 16:51
1. Can you give a little more detail about the wiki page event problem?
```
Context: Using the sample/*.json data? Working directly with GitLab? Sending custom data via cURL?
Command: `>embed TYPE` (if you used a bot command)
Error Message:  The result of your bot command, or the output from your console
```

2. I can't put a lot of detail in the config file itself, but I can create a wiki page explaining each part in more detail.

**Comment by ischon** [comment] 2018-01-03 16:57
I meant that the wiki page on the GitLab instance I use is not enabled, so it is logical that it doesn’t work. It was a mistake I made That generated the error I got

**Comment by ischon** [comment] 2018-01-03 17:01
And for the config maybe it is possible to use a umm file or create a JS file that exports an object with the configuration. If you don’t know how to do this with a JS file I can help with that

**Comment by 23nd** [comment] 2018-01-03 17:14
1. I can't imagine how you would get the error you describe, so I would like to reproduce it (or at least understand what you did).

- Testing with the sample data(`>embed wiki`) would not require an actual GitLab instance, and would not result in an error unless GitLab changed their json for wiki pages
- Creating a wiki page in your GitLab instance would mean you do have a wiki
- Using custom data via cURL would mean you define all the data to send to the webhook, so if you did this I'd like to see what data you sent

2. I want to keep the config file as simple as possible. JSON is a nice format for any user since the only way to break it is to forget a comma, quote, or bracket (all easily fixed with a good IDE or online validator).

**Comment by ischon** [comment] 2018-01-03 23:54
The error i got was in the webhook section. There is a test button to test every type of event. Because I use my own GitLab instance where wiki is disabled (so I’m not using GitLab.com) I got an error that wiki events didn’t work. It is nearly impossible to reproduce the error because it was caused by my GitLab instance settings

For the config: I respect your choice, and hope that you soon will add a better guide/tutorial on installing this tool

**Comment by ischon** [comment] 2018-01-03 23:56
I have crossed out wiki page events because I have no experience with actually using this type of event

**Comment by 23nd** [comment] 2018-01-05 00:43
Ahhh interesting! Last time I checked (like a year ago) there was only a single Test button for GitLab webhooks. It's good to know that there are test buttons for each type now, thank you.

Looking at the config file again, I noticed a lot of the properties could be made optional and initialized to default values. I may wait to post a better config guide next week after some much needed refactoring.

Will focus on implementing the last three event types tomorrow.

**Comment by ischon** [comment] 2018-01-05 06:54
Okay, it is nice to hear that probably in a week there will be an update, thanx a lot. Can’t wait to test it

**Comment by 23nd** [comment] 2018-01-08 09:51
Here's some previews of the Tag, Job/Build, and Pipeline event embeds: https://imgur.com/a/RDLX9
If you have any specific changes you'd like to see in the formatting, or if there's some data that you think should be included in the embeds, please make a new issue tagged `enhancement`.

The API added Confidential Issue hooks which I'll look into adding later this week before refactoring.

**Comment by ischon** [comment] 2018-01-08 10:07
Nice will be looking forward to start using it

**Comment by ischon** [comment] 2018-01-24 18:57
are you getting it done or don't you have time at the moment?  
just asking because of curiosity

**Comment by 23nd** [comment] 2018-04-05 21:43
Ah sorry, I got caught up in an influx of new work. 

I'll close this issue since the new hooks have been added to master branch.

The config refactor will be tracked in a new issue #9

**Closed as completed by 23nd** 2018-04-05 21:43 UTC
